# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

by MIGUEL, Letizha Martha C. | Section: 2ECE-D

This experiment focuses on fundamental array manipulation and analysis using the NumPy library.

**A. REPRODUCIBLE NORMALIZATION PROBLEM**

In [103]:
import numpy as np

In [104]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5,5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]], dtype=int32)

In [105]:
x̄ = np.mean(X)
x̄

np.float64(46.36)

In [106]:
σ = np.std(X)
σ

np.float64(25.864075471588002)

In [107]:
X_normalized = (X - x̄)/σ
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [108]:
x̄nmlzd = np.mean(X_normalized)
x̄nmlzd

np.float64(0.0)

In [109]:
σnmlzd = np.std(X_normalized)
σnmlzd

np.float64(0.9999999999999999)

In [110]:
print("Array X", X)

Array X [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [111]:
print("Normalized X Array", X_normalized)

Normalized X Array [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [112]:
print("Normalized Mean = ", x̄nmlzd)

Normalized Mean =  0.0


In [113]:
print("Normalized Standard Deviation = ", σnmlzd)

Normalized Standard Deviation =  0.9999999999999999


In [114]:
np.save('X_normalized.npy', X_normalized)

**B. CUBES DIVISIBLE BY 4 PROBLEM**

In [115]:
integers = np.arange(1, 101)

cubed_integers = integers**3

C = cubed_integers.reshape(10, 10)
display(C)

array([[      1,       8,      27,      64,     125,     216,     343,
            512,     729,    1000],
       [   1331,    1728,    2197,    2744,    3375,    4096,    4913,
           5832,    6859,    8000],
       [   9261,   10648,   12167,   13824,   15625,   17576,   19683,
          21952,   24389,   27000],
       [  29791,   32768,   35937,   39304,   42875,   46656,   50653,
          54872,   59319,   64000],
       [  68921,   74088,   79507,   85184,   91125,   97336,  103823,
         110592,  117649,  125000],
       [ 132651,  140608,  148877,  157464,  166375,  175616,  185193,
         195112,  205379,  216000],
       [ 226981,  238328,  250047,  262144,  274625,  287496,  300763,
         314432,  328509,  343000],
       [ 357911,  373248,  389017,  405224,  421875,  438976,  456533,
         474552,  493039,  512000],
       [ 531441,  551368,  571787,  592704,  614125,  636056,  658503,
         681472,  704969,  729000],
       [ 753571,  778688,  804357,  8

In [116]:
div_by_4 = C[C % 4 == 0]

print("Shape of C:", C.shape)
print("Array div_by_4:", div_by_4)
print("Number of selected elements:", div_by_4.size)

Shape of C: (10, 10)
Array div_by_4: [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
Number of selected elements: 50


In [117]:
np.save('div_by_4.npy', div_by_4)

**C. ABOVE-MEAN SQUARES PROBLEM**

In [118]:
integers_36 = np.arange(1, 37)

squared_integers = integers_36**2

S = squared_integers.reshape(6, 6)
display(S)

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [119]:
S_mean = np.mean(S)

above_mean = S[S > S_mean]

print("Array S:", S)
print("Mean of S (S_mean):", S_mean)

Array S: [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
Mean of S (S_mean): 450.1666666666667


In [120]:
print("Elements strictly greater than S_mean (above_mean):")
display(above_mean)
print("Number of selected elements:", above_mean.size)

Elements strictly greater than S_mean (above_mean):


array([ 484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296])

Number of selected elements: 15


In [121]:
np.save('above_mean.npy', above_mean)